apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-auth
  template:
    metadata:
      labels:
        app: ticket-auth
    spec:
      containers:
      - name: auth
        image: shridutt28/ticket-auth:latest
        imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: auth-srv
spec:
  type: ClusterIP
  selector:
    app: ticket-auth
  ports:
  - name: ticketing-auth
    protocol: TCP
    port: 3000
    targetPort: 3000

